### PR TITLE
Use the description/format string on Mac OS rather than the actual type.

### PR DESCRIPTION
**Pull request by StephanvanSchaik**
This PR addresses issue #32. Mac OS provides a much simpler list of `CTLTYPE_` constants as shown [here](https://github.com/apple/darwin-xnu/blob/main/bsd/sys/sysctl.h#L148) which does not include `CTLTYPE_ULONG` among others. Instead Mac OS provides a format string for the `sysctl` tool to use to know the width of an integer, and in general to know what the exact type of the value is supposed to be as described [here](https://github.com/apple/darwin-xnu/blob/main/bsd/sys/sysctl.h#L332). This PR modified the Mac OS code path to parse the format string to derive the actual type.

### CODE REVIEW

**Comment by StephanvanSchaik** [comment]
Apparently when the format string is specified for struct it may be of the form: "S,struct name", as shown [here](https://github.com/apple/darwin-xnu/blob/main/bsd/kern/kern_clock.c#L266) for the `kern.clockrate` sysctl. So I decided to only check the format string for `CtlType::Int` and either passthrough the `ctl_type` or only check `ctl_type` for the other variants.

This should be ready for review.

**Review by orhun — APPROVED** [review]

**Comment by johalun** [comment]
Thanks for this! Can you squash the commits before I merge?

**Comment by StephanvanSchaik** [comment]
You are welcome!

I squashed the commits and wrote both a short and a long descriptive commit message.

**Comment by johalun** [comment]
Excellent. Thank you!

**Pull request merged**
